name: 'lvs'

x-sentry-depends: &sentry-depends
    sentry-redis:
        condition: service_healthy
    sentry-postgres:
        condition: service_healthy

x-sentry-base: &sentry-base
    image: sentry:${LVS_SENTRY_VERSION:-9.1}
    environment:
        SENTRY_SECRET_KEY: '${LVS_SENTRY_SECRET_KEY:-"5%05(6a7+69a^e2f@*kw9_di##@kfdf%5ekci02ewd+7b=k6&z"}'
        SENTRY_REDIS_HOST: sentry-redis
        SENTRY_POSTGRES_HOST: sentry-postgres
        SENTRY_DB_USER: '${LVS_SENTRY_DB_USERNAME:-sentry}'
        SENTRY_DB_PASSWORD: '${LVS_SENTRY_DB_PASSWORD:-sentry}'
    networks:
        - lvs-sentry
    depends_on:
        <<: *sentry-depends
        sentry-upgrade:
            condition: service_completed_successfully
        sentry-create-user:
            condition: service_completed_successfully
    profiles:
        - all
        - logging
        - sentry

services:

    traefik:
        image: traefik:${LVS_TRAEFIK_VERSION:-3.0}
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.traefik.rule=Host(`traefik.${LVS_DOMAIN:-test}`)'
            - 'traefik.http.routers.traefik.service=api@internal'
            - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
        restart: unless-stopped
        environment:
            CF_DNS_API_TOKEN: '${LVS_TRAEFIK_CLOUDFLARE_TOKEN:-""}'
            CF_ZONE_API_TOKEN: '${LVS_TRAEFIK_CLOUDFLARE_TOKEN:-""}'
        ports:
            - '80:80'
            - '443:443'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command:
            - '--api=true'
            - '--log=true'
            - '--log.level=${LVS_LOG_LEVEL:-ERROR}'
            - '--accesslog=true'
            - '--ping=true'
            - '--ping.entryPoint=web'

            - '--metrics.prometheus=true'
            - '--metrics.prometheus.buckets=0.1,0.3,1.2,5.0,10.0'
            - '--metrics.prometheus.entrypoint=web'

            - '--providers.docker=true'
            - '--providers.docker.network=traefik'
            - '--providers.docker.network=${COMPOSE_PROJECT_NAME}_lvs'
            - '--providers.docker.defaultRule=Host(`{{ coalesce (index .Labels "com.docker.compose.project") (normalize .Name) }}.${LVS_DOMAIN:-test}`)'
            - '--providers.docker.exposedByDefault=false'
            - '--providers.docker.httpClientTimeout=900'

            - '--entrypoints.web=true'
            - '--entrypoints.web.address=:80'

            # <editor-fold desc="Let's encrypt">
            # Note: Uncomment everything below if you need https
            #- '--entrypoints.web.http.redirections.entrypoint.permanent=false'
            #- '--entrypoints.web.http.redirections.entrypoint.to=websecure'
            #- '--entrypoints.websecure=true'
            #- '--entrypoints.websecure.address=:443'
            #- '--entrypoints.websecure.http.tls=true'
            #- '--entrypoints.websecure.http.tls.certresolver=leresolver'
            #- '--entrypoints.websecure.http.tls.domains[0].main=${LVS_DOMAIN:-test}'
            #- '--entrypoints.websecure.http.tls.domains[0].sans=*.${LVS_DOMAIN:-test}'
            #- '--certificatesresolvers.leresolver=true'
            #- '--certificatesresolvers.leresolver.acme.email=${LVS_TRAEFIK_LETSENCRYPT_EMAIL:-"admin@example.com"}'
            #- '--certificatesresolvers.leresolver.acme.caServer=${LVS_TRAEFIK_LETSENCRYPT_SERVER:-"https://acme-staging-v02.api.letsencrypt.org/directory"}'
            #- '--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme-v2.json'
            #- '--certificatesresolvers.leresolver.acme.tlschallenge=false'
            #- '--certificatesresolvers.leresolver.acme.dnschallenge=true'
            #- '--certificatesresolvers.leresolver.acme.dnschallenge.delaybeforecheck=15'
            #- '--certificatesresolvers.leresolver.acme.dnschallenge.provider=cloudflare'
            #- '--certificatesresolvers.leresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53'
            # </editor-fold>
        volumes:
            - '${LVS_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro'
            - '${LVS_TRAEFIK_CERTS_VOLUME:-traefik-letsencrypt}:/letsencrypt:Z'
        networks:
            - traefik
            - lvs
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--spider", "http://healthcheck.${LVS_DOMAIN:-test}/ping" ]
            retries: 3
            timeout: 5s

    # <editor-fold desc="Management">
    portainer:
        image: portainer/portainer-ce:${LVS_PORTAINER_VERSION:-2.19}-alpine
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.portainer.rule=Host(`portainer.${LVS_DOMAIN:-test}`)'
            - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '${LVS_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro'
            - '${LVS_PORTAINER_VOLUME:-portainer-data}:/data'
        networks:
            - lvs
        profiles:
            - all
            - portainer
            - management

    registry:
        image: registry:${LVS_REGISTRY_VERSION:-2.8}
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.registry.rule=Host(`registry.${LVS_DOMAIN:-test}`)'
            - 'traefik.http.services.registry.loadbalancer.server.port=5000'
        restart: unless-stopped
        volumes:
            - '${LVS_REGISTRY_VOLUME:-registry-data}:/var/lib/registry'
        networks:
            - lvs
        profiles:
            - all
            - registry
            - management

    registry-hub:
        image: konradkleine/docker-registry-frontend:${LVS_REGISTRY_HUB_VERSION:-v2}
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.portainer.rule=Host(`hub.registry.${LVS_DOMAIN:-test}`)'
        restart: unless-stopped
        environment:
            ENV_DOCKER_REGISTRY_HOST: 'registry'
            ENV_DOCKER_REGISTRY_PORT: 5000
            ENV_MODE_BROWSE_ONLY: true
        networks:
            - lvs
        profiles:
            - all
            - registry
            - management
    # </editor-fold>

    # <editor-fold desc="Knowledge Base">
    knowledge:
        image: gollumwiki/gollum:${LVS_KNOWLEDGE_VERSION:-5.3}
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.knowledge.rule=Host(`knowledge.${LVS_DOMAIN:-test}`)'
            - 'traefik.http.services.knowledge.loadbalancer.server.port=4567'
        environment:
            GOLLUM_AUTHOR_USERNAME: '${LVS_KNOWLEDGE_AUTHOR_NAME:-Knowledge Base}'
            GOLLUM_AUTHOR_EMAIL: '${LVS_KNOWLEDGE_AUTHOR_EMAIL:-knowledge@example.com}'
        volumes:
            - '${LVS_KNOWLEDGE_VOLUME:-knowledge-data}:/wiki'
            - '${LVS_KNOWLEDGE_CONFIG:-/dev/null}:/etc/gollum/config.rb:ro'
        command:
            - '--mathjax'
            - '--local-time'
            - '--allow-uploads=page'
            - '--user-icons=gravatar'
            - '--config=/etc/gollum/config.rb'
        networks:
            - lvs
        profiles:
            - all
            - knowledge
    # </editor-fold>

    # <editor-fold desc="IDE">
    jetbrains:
        build:
            context: build/jetbrains
            args:
                USERNAME: '${LVS_JETBRAINS_USERNAME:-lvs}'
                PASSWORD: '${LVS_JETBRAINS_PASSWORD:-lvs}'
                LVSGROUP: '${LVS_JETBRAINS_GROUP_ID:-20}'
        ports:
            - '${LVS_JETBRAINS_PORT:-4467}:22'
        volumes:
            - '${LVS_JETBRAINS_PROJECTS:-jetbrains-projects}:/home/lvs/projects'
            - '${LVS_JETBRAINS_CACHE:-jetbrains-cache}:/home/lvs/.cache/JetBrains'
            - '${LVS_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro'
        profiles:
            - all
            - jetbrains
            - ide
    # </editor-fold>

    # <editor-fold desc="Sentry">
    sentry:
        << : *sentry-base
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.sentry.rule=Host(`sentry.${LVS_DOMAIN:-test}`)'
            - 'traefik.http.services.sentry.loadbalancer.server.port=9000'
        networks:
            - lvs
            - lvs-sentry
    sentry-upgrade:
        <<: *sentry-base
        depends_on:
            <<: *sentry-depends
        command: [ 'upgrade', '--noinput', '--traceback', '--verbosity', '0' ]
    sentry-create-user:
        <<: *sentry-base
        depends_on:
            <<: *sentry-depends
            sentry-upgrade:
                condition: service_completed_successfully
        command: [ 'createuser', '--email=sentry','--password=sentry',  '--no-superuser', '--no-input' ]
    sentry-cron:
        << : *sentry-base
        command: [ 'run', 'cron' ]
    sentry-worker:
        << : *sentry-base
        command: [ 'run', 'worker' ]
    sentry-redis:
        image: redis:${LVS_SENTRY_REDIS_VERSION:-7.2}-alpine
        volumes:
            - '${LVS_SENTRY_REDIS_VOLUME:-sentry-redis}:/data'
        networks:
            - lvs-sentry
        profiles:
            - all
            - logging
            - sentry
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
    sentry-postgres:
        image: postgres:${LVS_SENTRY_POSTGRES_VERSION:-16.1}-alpine
        environment:
            POSTGRES_USER: '${LVS_SENTRY_DB_USERNAME:-sentry}'
            POSTGRES_PASSWORD: '${LVS_SENTRY_DB_PASSWORD:-sentry}'
        volumes:
            - '${LVS_SENTRY_DB_VOLUME:-sentry-postgres}:/var/lib/postgresql/data'
        networks:
            - lvs-sentry
        profiles:
            - all
            - logging
            - sentry
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${LVS_SENTRY_DB_USERNAME:-sentry}" ]
    # </editor-fold>

volumes:
    jetbrains-cache:
        driver: local
    jetbrains-projects:
        driver: local
    knowledge-data:
        driver: local
    portainer-data:
        driver: local
    registry-data:
        driver: local
    sentry-postgres:
        driver: local
    sentry-redis:
        driver: local
    traefik-letsencrypt:
        driver: local

networks:
    lvs:
        driver: bridge
    lvs-sentry:
        driver: bridge
    traefik:
        external: true
