services:
  laravel.test:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.s3n.loadbalancer.server.port=80' # If expose port not 80
    networks:
      - traefik

networks:
  traefik:
    external: true
