version: '3'

services:

  traefik:
    image: traefik:2.5
    container_name: traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.${LVS_DOMAIN:-test}`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
    restart: always
    environment:
      LVS_DOMAIN: ${LVS_DOMAIN:-test}
      LVS_LETSENCRYPT_EMAIL: ${LVS_LETSENCRYPT_EMAIL:-"admin@example.com"}
      LVS_LETSENCRYPT_SERVER: ${LVS_LETSENCRYPT_SERVER:-"https://acme-staging-v02.api.letsencrypt.org/directory"}
      CF_DNS_API_TOKEN: ${LVS_CLOUDFLARE_TOKEN}
      CF_ZONE_API_TOKEN: ${LVS_CLOUDFLARE_TOKEN}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'traefik_letsencrypt:/letsencrypt'
      - './traefik.yml:/etc/traefik/traefik.yml'
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - traefik

  portainer:
    image: portainer/portainer-ce:2.6.2-alpine
    container_name: portainer
    profiles:
      - all
      - management
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`portainer.${LVS_DOMAIN:-test}`)'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - 'traefik.http.routers.portainer.tls=true'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    networks:
      - traefik

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    profiles:
      - all
      - metrics
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.${LVS_DOMAIN:-test}`)'
      - 'traefik.http.routers.prometheus.entrypoints=websecure'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
    networks:
      - traefik

volumes:
  portainer_data:
  traefik_letsencrypt:

networks:
  traefik:
    external: true
